### ISSUE TITLE
Fan is constantly on using the latest balena build

### ISSUE THREAD

**Issue by mikhail-vl** [balena-os/balena-jetson-orin#13]
I have two Orins on the table next to each other. One of them running native OS and another one has the latest balena build.

  Orin with nativeOS is warmer and fan is off. Orin with the latest balena build much colder. Fan is always on and it's noisy.

  Do you need to improve fan management, how does it work?

**Comment by acostach** [comment]
Hi @mikhail-vl, I'm not sure how the fan works on the new L4T for the Orin. Does it make any difference if you change the power models with jetson_clocks in the container?

**Comment by mikhail-vl** [comment]
@acostach Thank you for looking into it. A constantly working fan is not an issue for our deployments, which works stable, and we have no issues so far.

  Appreciate the support! We will wait for the official image with fan updates.

**Comment by acostach** [comment]
@mikhail-vl thank you for testing the image, glad to hear it's working as expected.

I've deployed 2.106.1 in staging for now, both the display port and the fan work fine for me in this version. You'll need to use the new version of jetson-flash at v0.5.32 if you want to check this new release because I updated the partition layout after doing some fixes in the image. The same jetson-flash revision or newer will be used with the production release in balena-cloud.

The plan is to release it to production in the next weeks, as soon as possible, after we fix some issues in the OS which are unrelated to the Orin. Again, please don't use staging for any production devices that will be deployed in the field or shipped to third parties because those will need to be re-flashed once the production images are out.

Thanks

**Comment by mikhail-vl** [comment]
@acostach Thank you for the update. I will test the new build later today to confirm.

  We totally understand the risk and use Orins in our controlled environments to prepare for the Production release.

**Comment by mikhail-vl** [comment]
@acostach Image and fan are working as expected. We will continue testing and monitoring over the week.

  I will let you know if there is anything else.
