### ISSUE TITLE
Add L4T 36.3 support for Jetson Orin device-types

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-jetson-orin#464]
Support is now merged and draft releases at v5.3.22 have been deployed for the Orin device-types

**Comment by mgabeler-lee-6rs** [comment]
@acostach Thanks, I'll give that a try and let you know how it goes (probably tomorrow as I'm physically away from my devkit today)

**Comment by mgabeler-lee-6rs** [comment]
@acostach after the OS & DTB update, the example container works ... ish. The XFCE desktop shows up on boot, but only momentarily, before the screen goes black (active output of all black pixels, not a DPMS power-save mode). Disconnecting & reconnecting the display brings the screen back, but only for a moment, as does changing the screen resolution from an ssh session using `xrandr`. Keyboard/mouse interaction works, even in the blacked-out state, but doesn't un-blackout the output, so I don't think this is caused by any "screen lock" type software.

Sensible-looking output appears in `/var/log/Xorg.0.log` when disconnecting/reconnecting the monitor, but nothing is reported there when the screen goes black. Some `dmesg` output appears when disconnecting the monitor (a couple dozen repeats of `NVRM rpcRmApiControl_dce: NVRM_RPC_DCE: Failed RM ctrl call cmd:0x731341 result 0xffff`, I'm assuming this is a harmless result of the unplug), but nothing when reconnecting it nor when it goes black again.

I tried this with two "spare" monitors I have on hand. One is an ELO brand 720p touchscreen (the same one we use in our product), the other is a "Eyoyo" thing (random cheapo item from Amazon). Both are going through a Pluggable (brand) DP->HDMI converter. The same converter & ELO monitor worked without incident in the Ubuntu install provided by nVidia on the devkit, though that may have been an L4T r35 based install.

**Comment by mgabeler-lee-6rs** [comment]
> The root filesystem is read-only in balenaOS, so if you want to start with a specific power model you can remount the rootfs as writable , edit /etc/nvpmodel.conf to set the default power model and reboot for the change to be picked up

This doesn't seem to work, and in a destructive way. The first time I tried it, it didn't stick -- after a reboot, it came back at the same `-m 2` power mode. The second time I tried it, I think it may have stuck, but it soft-bricked the device. It took several power cycles before it would even load the EFI "bios" screen (did it maybe eventually give up and boot some backup image?). From there I got the balena splash screen briefly before it blacked out. The ethernet is getting a link, but not requesting a DHCP address, so I can't connect and it's basically soft-bricked and I am going to have to re-flash it.

Even without the risks of bricking the unit, we'll for sure want a more production-y way to do this in the future.

> This because in newer L4Ts nvpmodel requires a restart to pick up the change

Not your fault, but frustrating. I've tried to find some docs on _why_ this is the case, but without luck. Do you happen to know what this is about, because the contents of `nvpmodel.conf` suggest it's all just sysfs tunables it's mucking with. Does it also write something into bootloader settings?

**Comment by acostach** [comment]
Hi @mgabeler-lee-6rs and sorry to hear you encountered these issues.

I've let my AGX Orin Devkit 64GB run with the xfce app for about 6 hours yesterday, outputting to a DELL 23inch monitor using DP directly, without any issues. Done so both after using the OS upgrade method as well as from a direct flash. This was with power mode 0, and sticks after the reboot, unless I perform a hostOS update, which of course will switch to a new root filesystem.


```
root@eb9639a:~# nvpmodel -q
NV Power Mode: MAXN
0
root@eb9639a:~# free -h
              total        used        free      shared  buff/cache   available
Mem:       64352872     1291368    62580100       27316      481404    62478900
Swap:       4095996           0     4095996
root@eb9639a:~# systemctl | grep fail
root@eb9639a:~# uname -r
5.15.136-l4t-r36.3-1009.9
root@eb9639a:~# cat /etc/os-release 
ID="balena-os"
NAME="balenaOS"
VERSION="5.3.23"
VERSION_ID="5.3.23"
PRETTY_NAME="balenaOS 5.3.23"
DISTRO_CODENAME="kirkstone"
MACHINE="jetson-agx-orin-devkit"
META_BALENA_VERSION="5.3.23"
BALENA_BOARD_REV="69b3e46"
META_BALENA_REV="e6c20376"
SLUG="jetson-agx-orin-devkit"
root@eb9639a:~# ls -l /mnt/sysroot/active/current/boot/
total 74812
-rw-r--r-- 1 root root 66294272 Mar  9  2018 Image
drwxr-xr-x 2 root root     4096 Jul 17 09:43 devicetree
drwxr-xr-x 2 root root     4096 Jul 17 09:43 extlinux
-rwxr-xr-x 1 root root  9799208 Mar  9  2018 init
-rw-r--r-- 1 root root   249445 Mar  9  2018 tegra234-p3737-0000+p3701-0000-nv.dtb
-rw-r--r-- 1 root root   249470 Jul 17 09:46 tegra234-p3737-0000+p3701-0005-nv.dtb
root@eb9639a:~# cat /mnt/boot/extra_uEnv.txt 
custom_fdt_file=tegra234-p3737-0000+p3701-0005-nv.dtb
```

Today I've let the exact same setup run connected trough a no-name DP to HDMI adapter to a HP 23inch monitor. So far no problems whatsoever for the past 2 hours, and I did the switch directly from DP DELL to DP-HDMI HP..

If you have a microUSB cable, you an connect it to the microUSB port and then on your PC issue minicom -D /dev/ttyACM0. You'll need to make sure the OS is in development mode ("developmentMode": true in /mnt/boot/config.json) to get a console prompt. 

Since I'm not seeing any of these problems you encounter, I wonder if this is dtb related or could have anything to do with the displays. Probably best to tackle one at a time.

So, with the debug uart over the microUSB cable, first make sure you can log into to the host OS. Don't connect any display, and let's first see if the dtb is the right one by checking the boardspec:

```
root@eb9639a:~# tegra-boardspec 
3701-500-0005-M.0-1-0
```

On my 64GB AGX Orin I get SKU 0005 hence I use the 0005-nv.dtb.

Then, if the device was cleanly flashed with 5.3.23 and has the new dtb booted, first check if changing the default power model causes any trouble. This because:

> This doesn't seem to work, and in a destructive way. The first time I tried it, it didn't stick -- after a reboot, it came back at the same -m 2 power mode. The second time I tried it, I think it may have stuck, but it soft-bricked the device. 

i'm not sure if this operation was performed right after the OS upgrade, or after a re-flash. If you did this in the first minute or so right after the OS update, it is possible that the OS checks may have not completed, and the reboots caused it to fallback to the old OS, which doesn't support custom dtbs. After the OS update there are a couple files in `/mnt/state/rollback-*` which disappear once the update is completed successfully, usually in a couple minutes after booting the new OS. Any user initiated reboot can cause the device to rollback.

If the power model still isn't saved after the reboot, you can enable support access to the device and share its UUID with me so I can have a look.

If it stays as expected, you can then check if connecting to a normal PC screen changes anything, perhaps using the display port directly if available.

Apart from this, on my AGX Orin 64GB it's sufficient to unload the nvidia_drm module only, but on other Orin devices I observed that unloading nvidia_modeset was also needed: https://github.com/balena-io-examples/jetson-examples/blob/master/jetson-orin-nx-xavier-nx-devkit/Dockerfile#L55 - this could also be a root cause.

**Comment by acostach** [comment]
Just in case it helps, these are the errors I see in dmesg if the device-tree is not the right one, i.e using a 32GB dtb on the 64GB unit due to not setting the dtb:

```
[   70.800116] tegra-hsierrrptinj: Callback for 0x0001 already registered
[   70.800122] nvgpu: 17000000.gpu                nvgpu_cic_mon_init:75   [ERR]  Err inj callback registration failed: -22
[   70.854698] nvgpu: 17000000.gpu engine_fb_queue_set_element_use_state:144  [ERR]  FBQ last received queue element not processed yet queue_pos 0
[   70.854707] nvgpu: 17000000.gpu        nvgpu_engine_fb_queue_push:373  [ERR]  fb-queue element in use map is in invalid state
[   70.854708] nvgpu: 17000000.gpu        nvgpu_engine_fb_queue_push:401  [ERR]  falcon id-0, queue id-1, failed
[   70.854711] nvgpu: 17000000.gpu                     pmu_write_cmd:178  [ERR]  fail to write cmd to queue 1
[   70.854713] nvgpu: 17000000.gpu             nvgpu_pmu_rpc_execute:727  [ERR]  Failed to execute RPC status=0xffffffea, func=0x3
[   70.854715] nvgpu: 17000000.gpu gv100_pmu_lsfm_bootstrap_ls_falcon:100  [ERR]  Failed to execute RPC, status=0xffffffea
[   70.854716] nvgpu: 17000000.gpu nvgpu_pmu_lsfm_bootstrap_ls_falcon:128  [ERR]  LSF Load failed
[   70.854718] nvgpu: 17000000.gpu nvgpu_gr_falcon_load_secure_ctxsw_ucode:718  [ERR]  Unable to recover GR falcon
[   70.854719] nvgpu: 17000000.gpu        nvgpu_gr_falcon_init_ctxsw:156  [ERR]  fail
[   70.854723] nvgpu: 17000000.gpu nvgpu_cic_mon_report_err_safety_services:97   [ERR]  Error reporting is not supported in this platform
[   70.854724] nvgpu: 17000000.gpu      gr_init_ctxsw_falcon_support:857  [ERR]  FECS context switch init error
[   70.854726] nvgpu: 17000000.gpu            nvgpu_finalize_poweron:1095 [ERR]  Failed initialization for: g->ops.gr.gr_init_support
[   70.883611] nvgpu: 17000000.gpu                 gk20a_power_write:127  [ERR]  power_node_write failed at busy
```

**Comment by mgabeler-lee-6rs** [comment]
Given the monitor issue went away with a re-flash, I'm going to assume there was something related to the upgrade from L4T r35 to r36, or the DTBs. I'm not concerned with that any more, so long as it doesn't repeat, and if it does I'll try to get a more precise set of repro steps.

> If you did this in the first minute or so right after the OS update, it is possible that the OS checks may have not completed

While I don't recall timing for sure, this is entirely possible. I'll keep an eye out on the next attempt for the rollback files.

I'll give it another go with the dev mode & serial console enabled.

One question related to the remounting of the rootfs: It's an overlayfs, does `mount -o remount,rw /` actually do the right thing? I'm not familiar with tracing overlayfs configurations, where is the _actual_ storage for `/etc/nvpmodel.conf`?

Did you change the power mode(l) on yours by running `nvpmodel -m 0`, or just by editing that conf file?

**Comment by acostach** [comment]
> Given the monitor issue went away with a re-flash

That's something that I believe definitely needs reproducing again @mgabeler-lee-6rs  , perhaps try again an update on the next draft release? As I was saying I'm not able to reproduce this at all, neither with the draft OS upgrade nor with flashing from scratch, so it would be a good opportunity to understand what caused that.

> Edit: last time I had mostly been doing nvpmodel -m 0 to change things. This time I did it by editing the conf file and with more careful use of sync before rebooting and whatnot. It ... seems to have worked this time 😀

I've never used `nvpmodel -m 0`, so I'm not sure how it works exactly but it never saved any value I set, this is why I was recommending editing the file directly, which always works as expected.

I'd have to build and include strace in an image while removing the reboot possibility to see how exactly it works and if it actually writes directly to /etc/nvpmodel.conf, or if there's something else involved. It might be that nvpmodel forces a reboot right away without flushing the disk (sync), which would explain why the change isn't saved with it.

**Comment by acostach** [comment]
All Orin DTs are now based on L4T 36.3
